/*globals define, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Sun Nov 26 2023 23:10:44 GMT+0000 (Coordinated Universal Time).
 */

define([
    'js/Constants',
    'js/Utils/GMEConcepts',
    'js/NodePropertyNames',
    'othello-miniproject/constants'
], function (
    CONSTANTS,
    GMEConcepts,
    nodePropertyNames,
    OTHELLO_CONSTANTS
) {

    'use strict';

    function ReactOthelloControl(options) {

        this._logger = options.logger.fork('Control');

        this._client = options.client;

        this._currentNodeId = null;
        this._currentNodeParentId = undefined;

        this._updateWidget = null;
        this._descriptor = null;

        this._logger.debug('ctor finished');

        //TODO: this information should be gathered from the META
        // both are Piece Meta (with color attribute)  
        this._piece_black = '/n/L';
        this._piece_white = '/n/L';
    }

    ReactOthelloControl.prototype.registerUpdate = function (func) {
        console.log('trying to register...');
        const firstTry = this._updateWidget === null ? true : false;
        this._updateWidget = func;
        if(this._descriptor && firstTry) {
            this._updateWidget(this._descriptor);
        }
    };
    
    /**
    ReactOthelloControl.prototype._initWidgetEventHandlers = function () {
        this._widget.onNodeClick = function (id) {
            // Change the current active object
            WebGMEGlobal.State.registerActiveObject(id);
        };
    };
    */
/* * * * * * * * Visualizer content update callbacks * * * * * * * */
    // One major concept here is with managing the territory. The territory
    // defines the parts of the project that the visualizer is interested in
    // (this allows the browser to then only load those relevant parts).
    ReactOthelloControl.prototype.selectedObjectChanged = function (nodeId) {
        const {_logger, _client} = this;
        console.log('in selectedObjectChanged');
        _logger.debug('activeObject nodeId \'' + nodeId + '\'');

        // Remove current territory patterns
        if (this._currentNodeId) {
            _client.removeUI(this._territoryId);

        }

        this._currentNodeId = nodeId;
        this._currentNodeParentId = _client.getNode(this._currentNodeId).getParentId();

        if (typeof this._currentNodeId === 'string') {
            // Put new node's info into territory rules
            this._selfPatterns = {};
            // 4 since OthellOGame contains OthellOGameState
                    // OthelloGameState contains Player and Board
                    // Board contains Tile
                    // Tile contains Piece
            this._selfPatterns[this._currentNodeId] = {children: 4}; //all workflows in the project

            this._territoryId = _client.addUI(this, events => {
                this._eventCallback(events);
            });

            // Update the territory
            _client.updateTerritory(this._territoryId, this._selfPatterns);
        }
    };

    ReactOthelloControl.prototype._createDescriptor = function () {
        console.log('in creating descirptor in reactothellocontrol');
        const {_client, _META, _currentNodeId, _logger} = this;
        if (typeof _currentNodeId === 'string') {
            const context = _client.getCurrentPluginContext('BuildDescriptor');
            context.managerConfig.activeNode = _currentNodeId;
            context.managerConfig.namespace = null;
            context.pluginConfig = {};

            _client.runServerPlugin('BuildDescriptor', context, (err, result)=>{
                // console.log('export:', err, result);
                if (err === null && result && result.success) {
                    const descriptor = JSON.parse(result.messages[0].message);
                    this._descriptor = descriptor;
                    if(this._updateWidget) {
                        this._updateWidget(descriptor);
                    }
                } else {
                    //TODO - make a proper way of handling this
                    _logger.error('Failed to collect descriptor', err);
                }
            });
        }
    };

    ReactOthelloControl.prototype.playerMoves = function (player, position) {
        console.log(player, position);
        const {_client, _currentNodeId, _logger} = this;
        if (typeof _currentNodeId === 'string') {
            const context = _client.getCurrentPluginContext('PlayerMoves');
            context.managerConfig.activeNode = _currentNodeId;
            context.managerConfig.namespace = null;
            context.pluginConfig = {position};

            _client.runServerPlugin('PlayerMoves', context, (err, result)=>{
                // console.log('export:', err, result);
                if (err === null && result && result.success) {
                    //TODO: - there is nothing to do as the plugin updated the model
                } else {
                    //TODO - make a proper way of handling this
                    _logger.error('Failed to make move', err);
                }
            });
        }
    }
    /* * * * * * * * Node Event Handling * * * * * * * */
    ReactOthelloControl.prototype._eventCallback = function (events) {
        var i = events ? events.length : 0,
            event;

        this._logger.debug('_eventCallback \'' + i + '\' items');
        // if(this._updateWidget !== null) {
            // console.log('we got widget connection');
            // this._updateWidget([],[],{});
        // }

        if (events[0] && events[0].etype === 'complete') {
            //we have what we need
            this._createDescriptor();
        }
        this._logger.debug('_eventCallback \'' + events.length + '\' items - DONE');
    };

    // ReactOthelloControl.prototype._onLoad = function (gmeId) {
    //     var description = this._getObjectDescriptor(gmeId);
    //     this._widget.addNode(description);
    // };

    // ReactOthelloControl.prototype._onUpdate = function (gmeId) {
    //     var description = this._getObjectDescriptor(gmeId);
    //     this._widget.updateNode(description);
    // };

    // ReactOthelloControl.prototype._onUnload = function (gmeId) {
    //     this._widget.removeNode(gmeId);
    // };

    ReactOthelloControl.prototype._stateActiveObjectChanged = function (model, activeObjectId) {
        if (this._currentNodeId === activeObjectId) {
            // The same node selected as before - do not trigger
        } else {
            this.selectedObjectChanged(activeObjectId);
        }
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    ReactOthelloControl.prototype.destroy = function () {
        this._detachClientEventListeners();
        this._removeToolbarItems();
        this._updateWidget = null;
    };

    ReactOthelloControl.prototype._attachClientEventListeners = function () {
        this._detachClientEventListeners();
        WebGMEGlobal.State.on('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged, this);
    };

    ReactOthelloControl.prototype._detachClientEventListeners = function () {
        WebGMEGlobal.State.off('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged);
    };

    ReactOthelloControl.prototype.onActivate = function () {
        this._attachClientEventListeners();
        this._displayToolbarItems();

        if (typeof this._currentNodeId === 'string') {
            //  trying to force a refresh in case of activation
            const nodeId = this._currentNodeId;
            this._currentNodeId = null;
            WebGMEGlobal.State.registerActiveObject(nodeId, {suppressVisualizerFromNode: true});
        }
    };

    ReactOthelloControl.prototype.onDeactivate = function () {
        this._detachClientEventListeners();
        this._hideToolbarItems();
        this._updateWidget = null;
    };

    /* * * * * * * * * * Updating the toolbar * * * * * * * * * */
    ReactOthelloControl.prototype._displayToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].show();
            }
        } else {
            this._initializeToolbar();
        }
    };

    ReactOthelloControl.prototype._hideToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].hide();
            }
        }
    };

    ReactOthelloControl.prototype._removeToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].destroy();
            }
        }
    };

    ReactOthelloControl.prototype._initializeToolbar = function () {
        const {_client, _logger} = this;
        var self = this,
            toolBar = WebGMEGlobal.Toolbar;

        this._toolbarItems = [];

        this._toolbarItems.push(toolBar.addSeparator());

        /************** Go to hierarchical parent button ****************/
        this.$btnNewGame = toolBar.addButton({
            title: 'Start new game',
            icon: 'glyphicon glyphicon-plus',
            clickFn: function (/*data*/) {
                const context = _client.getCurrentPluginContext('CreateGame');
                context.managerConfig.activeNode = self._currentNodeParentId;
                context.managerConfig.namespace = null;
                context.pluginConfig = {};

                _client.runServerPlugin('CreateGame', context, (err, result)=>{
                    // console.log('export:', err, result);
                    if (err === null && result && result.success) {
                        //TODO: - there is nothing to do as the plugin updated the model
                        const newGamePath = result.messages[0].message;
                        WebGMEGlobal.State.registerActiveObject(newGamePath);
                        WebGMEGlobal.State.registerActiveVisualizer('ReactOthello');
                    } else {
                        //TODO - make a proper way of handling this
                        _logger.error('Failed to initiate new game', err);
                    }
                });
            }
        });
        this._toolbarItems.push(this.$btnNewGame);
        this.$btnNewGame.hide();

        this.$btnNewGame = toolBar.addButton({
            title: 'Undo',
            icon: 'glyphicon glyphicon-circle-arrow-left',
            clickFn: function (/*data*/) {
                const context = _client.getCurrentPluginContext('Undo');
                context.managerConfig.activeNode = self._currentNodeParentId;
                context.managerConfig.namespace = null;
                context.pluginConfig = {};

                _client.runServerPlugin('Undo', context, (err, result)=>{
                    // console.log('export:', err, result);
                    if (err === null && result && result.success) {
                        //TODO: - there is nothing to do as the plugin updated the model
                        const prevGameState = result.messages[0].message;
                        WebGMEGlobal.State.registerActiveObject(prevGameState);
                        WebGMEGlobal.State.registerActiveVisualizer('ReactOthello');
                    } else {
                        //TODO - make a proper way of handling this
                        _logger.error('Failed to initiate undo', err);
                    }
                });
            }
        });
        this._toolbarItems.push(this.$btnNewGame);
        this.$btnNewGame.hide();

        /************** Checkbox example *******************/

        // this.$cbShowConnection = toolBar.addCheckBox({
        //     title: 'toggle checkbox',
        //     icon: 'gme icon-gme_diagonal-arrow',
        //     checkChangedFn: function (data, checked) {
        //         self._logger.debug('Checkbox has been clicked!');
        //     }
        // });
        // this._toolbarItems.push(this.$cbShowConnection);

        this._toolbarInitialized = true;
    };

    return ReactOthelloControl;
});
